const input = [
    {
        isExternal: true,
        classValue: 3, //1, 2, 3
        coreSubjects: [
            {
            "coreSubject":"organizationalGovernance",
            "rating": 3
            },
            {
            "coreSubject":"humanRights",
            "rating": 4
            },
            {
            "coreSubject":"laborPractices",
            "rating": 5
            },
            {
            "coreSubject":"theEnvironment",
            "rating": 6
            },
            {
            "coreSubject":"fairOperatingPractices",
            "rating": 7
            },
            {
            "coreSubject":"consumerIssues",
            "rating": 2
            },
            {
            "coreSubject":"communityInvolvementAndDevelopment",
            "rating": 1
            }
        ],
        issueOfInterest: [
            {
                "coreSubject":"organizationalGovernance",
                "data":[
                    {
                        "issueOfInterest":"transparency",
                        "rating": 1
                    },
                    {
                        "issueOfInterest":"ethicalConduct",
                        "rating": 2
                    },
                    {
                        "issueOfInterest":"respectOfRuleOfLaw",
                        "rating": 3
                    },
                    {
                        "issueOfInterest":"accountability",
                        "rating": 4
                    },
                    {
                        "issueOfInterest":"corporateGovernance",
                        "rating": 5
                    }
                ]
            },
            {
                "coreSubject":"humanRights",
                "data":[
                    {
                        "issueOfInterest":"humanRightsRisksSituations",
                        "rating":1
                    },
                    {
                        "issueOfInterest":"dueDiligence",
                        "rating": 2
                    },
                    {
                        "issueOfInterest":"avoindanceOfComplicity",
                        "rating":3
                    },
                    {
                        "issueOfInterest":"resolvingGievances",
                        "rating":4
                    },
                    {
                        "issueOfInterest":"discriminationAndVulnerableGroups",
                        "rating":5
                    },
                    {
                        "issueOfInterest":"civilAndPoliticalRights",
                        "rating":6
                    },
                    {
                        "issueOfInterest":"economicSocialAndCulturalRights",
                        "rating":7
                    },
                    {
                        "issueOfInterest":"fundamentalPrinciplesAndRightsAtWork",
                        "rating":8
                    }
                ]
            },
            {
                "coreSubject":"laborPractices",
                "data":[
                    {
                        "issueOfInterest":"conditionsOfWorkAndSocialProtection",
                        "rating":1
                    },
                    {
                        "issueOfInterest":"employmentAndEmploymentRelationships",
                        "rating":2
                    },
                    {
                        "issueOfInterest":"socialDialogue",
                        "rating":3
                    },
                    {
                        "issueOfInterest":"healthAndSafetyAtWork",
                        "rating":4
                    },
                    {
                        "issueOfInterest":"humanDevelopmentAndTrainingInTheWorkplace",
                        "rating":5
                    }
                ]
                },
            {
                "coreSubject":"theEnvironment",
                "data":[
                    {
                        "issueOfInterest":"sustainableResourceUse",
                        "rating":1
                    },
                    {
                        "issueOfInterest":"preventionOfPollution",
                        "rating":2
                    },
                    {
                        "issueOfInterest":"climateChangeMitigationAndAdaptation",
                        "rating":3
                    },
                    {
                        "issueOfInterest":"ProtectionOfTheEnvironmentBiodiversityAndRestorationOfNaturalHabitats",
                        "rating":4
                    }
                ]
                },
            {
                "coreSubject":"fairOperatingPractices",
                "data":[
                        {
                            "issueOfInterest":"responsiblePoliticalInvolvement",
                            "rating":1
                        },
                        {
                            "issueOfInterest":"antiCorruption",
                            "rating":2
                        },
                        {
                            "issueOfInterest":"fairCompetition",
                            "rating":3
                        },
                        {
                            "issueOfInterest":"promotingSocialResponsibilityInTheValueChain",
                            "rating":4
                        },
                        {
                            "issueOfInterest":"respectForPropertyRights",
                            "rating":5
                        }
                    ]
                },
            {
                "coreSubject":"consumerIssues",
                "data": [
                    {
                        "issueOfInterest":"protectingConsumersHealthAndSafety",
                        "rating":1
                    },
                    {
                        "issueOfInterest":"fairMarketingFactualAndUnbiasedInformati",
                        "rating":2
                    },
                    {
                        "issueOfInterest":"sustainableConsumption",
                        "rating":3
                    },
                    {
                        "issueOfInterest":"consumerServiceSupportAndComplai",
                        "rating":4
                    },
                    {
                        "issueOfInterest":"consumerDataProtectionAndPrivacy",
                        "rating":5
                    },
                    {
                        "issueOfInterest":"accessToEssentialServices",
                        "rating":6
                    },
                    {
                        "issueOfInterest":"educationAndAwareness",
                        "rating":7
                    }
                ]
            },
            {
                "coreSubject":"communityInvolvementAndDevelopment",
                "data":[
                    {
                        "issueOfInterest":"educationAndCulture",
                        "rating":1
                    },
                    {
                        "issueOfInterest":"communityInvolvement",
                        "rating":2
                    },
                    {
                        "issueOfInterest":"employmentCreationAndSkillsDevelopment",
                        "rating":3
                    },
                    {
                        "issueOfInterest":"technologyDevelopmentAndAccess",
                        "rating":4
                    },
                    {
                        "issueOfInterest":"wealthAndIncomeCreation",
                        "rating":5
                    },
                    {
                        "issueOfInterest":"health",
                        "rating":6
                    },
                    {
                        "issueOfInterest":"socialInvestment",
                        "rating":7
                    }
                ]
            }
        ]
    },
    {
        isExternal: true,
        classValue: 3, //1, 2, 3
        coreSubjects: [
            {
            "coreSubject":"organizationalGovernance",
            "rating": 3
            },
            {
            "coreSubject":"humanRights",
            "rating": 4
            },
            {
            "coreSubject":"laborPractices",
            "rating": 5
            },
            {
            "coreSubject":"theEnvironment",
            "rating": 6
            },
            {
            "coreSubject":"fairOperatingPractices",
            "rating": 7
            },
            {
            "coreSubject":"consumerIssues",
            "rating": 2
            },
            {
            "coreSubject":"communityInvolvementAndDevelopment",
            "rating": 1
            }
        ],
        issueOfInterest: [
            {
                "coreSubject":"organizationalGovernance",
                "data":[
                    {
                        "issueOfInterest":"transparency",
                        "rating": 1
                    },
                    {
                        "issueOfInterest":"ethicalConduct",
                        "rating": 2
                    },
                    {
                        "issueOfInterest":"respectOfRuleOfLaw",
                        "rating": 3
                    },
                    {
                        "issueOfInterest":"accountability",
                        "rating": 4
                    },
                    {
                        "issueOfInterest":"corporateGovernance",
                        "rating": 5
                    }
                ]
            },
            {
                "coreSubject":"humanRights",
                "data":[
                    {
                        "issueOfInterest":"humanRightsRisksSituations",
                        "rating":1
                    },
                    {
                        "issueOfInterest":"dueDiligence",
                        "rating": 2
                    },
                    {
                        "issueOfInterest":"avoindanceOfComplicity",
                        "rating":3
                    },
                    {
                        "issueOfInterest":"resolvingGievances",
                        "rating":4
                    },
                    {
                        "issueOfInterest":"discriminationAndVulnerableGroups",
                        "rating":5
                    },
                    {
                        "issueOfInterest":"civilAndPoliticalRights",
                        "rating":6
                    },
                    {
                        "issueOfInterest":"economicSocialAndCulturalRights",
                        "rating":7
                    },
                    {
                        "issueOfInterest":"fundamentalPrinciplesAndRightsAtWork",
                        "rating":8
                    }
                ]
            },
            {
                "coreSubject":"laborPractices",
                "data":[
                    {
                        "issueOfInterest":"conditionsOfWorkAndSocialProtection",
                        "rating":1
                    },
                    {
                        "issueOfInterest":"employmentAndEmploymentRelationships",
                        "rating":2
                    },
                    {
                        "issueOfInterest":"socialDialogue",
                        "rating":3
                    },
                    {
                        "issueOfInterest":"healthAndSafetyAtWork",
                        "rating":4
                    },
                    {
                        "issueOfInterest":"humanDevelopmentAndTrainingInTheWorkplace",
                        "rating":5
                    }
                ]
                },
            {
                "coreSubject":"theEnvironment",
                "data":[
                    {
                        "issueOfInterest":"sustainableResourceUse",
                        "rating":1
                    },
                    {
                        "issueOfInterest":"preventionOfPollution",
                        "rating":2
                    },
                    {
                        "issueOfInterest":"climateChangeMitigationAndAdaptation",
                        "rating":3
                    },
                    {
                        "issueOfInterest":"ProtectionOfTheEnvironmentBiodiversityAndRestorationOfNaturalHabitats",
                        "rating":4
                    }
                ]
                },
            {
                "coreSubject":"fairOperatingPractices",
                "data":[
                        {
                            "issueOfInterest":"responsiblePoliticalInvolvement",
                            "rating":1
                        },
                        {
                            "issueOfInterest":"antiCorruption",
                            "rating":2
                        },
                        {
                            "issueOfInterest":"fairCompetition",
                            "rating":3
                        },
                        {
                            "issueOfInterest":"promotingSocialResponsibilityInTheValueChain",
                            "rating":4
                        },
                        {
                            "issueOfInterest":"respectForPropertyRights",
                            "rating":5
                        }
                    ]
                },
            {
                "coreSubject":"consumerIssues",
                "data": [
                    {
                        "issueOfInterest":"protectingConsumersHealthAndSafety",
                        "rating":1
                    },
                    {
                        "issueOfInterest":"fairMarketingFactualAndUnbiasedInformati",
                        "rating":2
                    },
                    {
                        "issueOfInterest":"sustainableConsumption",
                        "rating":3
                    },
                    {
                        "issueOfInterest":"consumerServiceSupportAndComplai",
                        "rating":4
                    },
                    {
                        "issueOfInterest":"consumerDataProtectionAndPrivacy",
                        "rating":5
                    },
                    {
                        "issueOfInterest":"accessToEssentialServices",
                        "rating":6
                    },
                    {
                        "issueOfInterest":"educationAndAwareness",
                        "rating":7
                    }
                ]
            },
            {
                "coreSubject":"communityInvolvementAndDevelopment",
                "data":[
                    {
                        "issueOfInterest":"educationAndCulture",
                        "rating":1
                    },
                    {
                        "issueOfInterest":"communityInvolvement",
                        "rating":2
                    },
                    {
                        "issueOfInterest":"employmentCreationAndSkillsDevelopment",
                        "rating":3
                    },
                    {
                        "issueOfInterest":"technologyDevelopmentAndAccess",
                        "rating":4
                    },
                    {
                        "issueOfInterest":"wealthAndIncomeCreation",
                        "rating":5
                    },
                    {
                        "issueOfInterest":"health",
                        "rating":6
                    },
                    {
                        "issueOfInterest":"socialInvestment",
                        "rating":7
                    }
                ]
            }
        ]
    },
    {
        isExternal: false,
        classValue: 3, //1, 2, 3
        coreSubjects: [
            {
            "coreSubject":"organizationalGovernance",
            "rating": 3
            },
            {
            "coreSubject":"humanRights",
            "rating": 4
            },
            {
            "coreSubject":"laborPractices",
            "rating": 5
            },
            {
            "coreSubject":"theEnvironment",
            "rating": 6
            },
            {
            "coreSubject":"fairOperatingPractices",
            "rating": 7
            },
            {
            "coreSubject":"consumerIssues",
            "rating": 2
            },
            {
            "coreSubject":"communityInvolvementAndDevelopment",
            "rating": 1
            }
        ],
        issueOfInterest: [
            {
                "coreSubject":"organizationalGovernance",
                "data":[
                    {
                        "issueOfInterest":"transparency",
                        "rating": 1
                    },
                    {
                        "issueOfInterest":"ethicalConduct",
                        "rating": 2
                    },
                    {
                        "issueOfInterest":"respectOfRuleOfLaw",
                        "rating": 3
                    },
                    {
                        "issueOfInterest":"accountability",
                        "rating": 4
                    },
                    {
                        "issueOfInterest":"corporateGovernance",
                        "rating": 5
                    }
                ]
            },
            {
                "coreSubject":"humanRights",
                "data":[
                    {
                        "issueOfInterest":"humanRightsRisksSituations",
                        "rating":1
                    },
                    {
                        "issueOfInterest":"dueDiligence",
                        "rating": 2
                    },
                    {
                        "issueOfInterest":"avoindanceOfComplicity",
                        "rating":3
                    },
                    {
                        "issueOfInterest":"resolvingGievances",
                        "rating":4
                    },
                    {
                        "issueOfInterest":"discriminationAndVulnerableGroups",
                        "rating":5
                    },
                    {
                        "issueOfInterest":"civilAndPoliticalRights",
                        "rating":6
                    },
                    {
                        "issueOfInterest":"economicSocialAndCulturalRights",
                        "rating":7
                    },
                    {
                        "issueOfInterest":"fundamentalPrinciplesAndRightsAtWork",
                        "rating":8
                    }
                ]
            },
            {
                "coreSubject":"laborPractices",
                "data":[
                    {
                        "issueOfInterest":"conditionsOfWorkAndSocialProtection",
                        "rating":1
                    },
                    {
                        "issueOfInterest":"employmentAndEmploymentRelationships",
                        "rating":2
                    },
                    {
                        "issueOfInterest":"socialDialogue",
                        "rating":3
                    },
                    {
                        "issueOfInterest":"healthAndSafetyAtWork",
                        "rating":4
                    },
                    {
                        "issueOfInterest":"humanDevelopmentAndTrainingInTheWorkplace",
                        "rating":5
                    }
                ]
                },
            {
                "coreSubject":"theEnvironment",
                "data":[
                    {
                        "issueOfInterest":"sustainableResourceUse",
                        "rating":1
                    },
                    {
                        "issueOfInterest":"preventionOfPollution",
                        "rating":2
                    },
                    {
                        "issueOfInterest":"climateChangeMitigationAndAdaptation",
                        "rating":3
                    },
                    {
                        "issueOfInterest":"ProtectionOfTheEnvironmentBiodiversityAndRestorationOfNaturalHabitats",
                        "rating":4
                    }
                ]
                },
            {
                "coreSubject":"fairOperatingPractices",
                "data":[
                        {
                            "issueOfInterest":"responsiblePoliticalInvolvement",
                            "rating":1
                        },
                        {
                            "issueOfInterest":"antiCorruption",
                            "rating":2
                        },
                        {
                            "issueOfInterest":"fairCompetition",
                            "rating":3
                        },
                        {
                            "issueOfInterest":"promotingSocialResponsibilityInTheValueChain",
                            "rating":4
                        },
                        {
                            "issueOfInterest":"respectForPropertyRights",
                            "rating":5
                        }
                    ]
                },
            {
                "coreSubject":"consumerIssues",
                "data": [
                    {
                        "issueOfInterest":"protectingConsumersHealthAndSafety",
                        "rating":1
                    },
                    {
                        "issueOfInterest":"fairMarketingFactualAndUnbiasedInformati",
                        "rating":2
                    },
                    {
                        "issueOfInterest":"sustainableConsumption",
                        "rating":3
                    },
                    {
                        "issueOfInterest":"consumerServiceSupportAndComplai",
                        "rating":4
                    },
                    {
                        "issueOfInterest":"consumerDataProtectionAndPrivacy",
                        "rating":5
                    },
                    {
                        "issueOfInterest":"accessToEssentialServices",
                        "rating":6
                    },
                    {
                        "issueOfInterest":"educationAndAwareness",
                        "rating":7
                    }
                ]
            },
            {
                "coreSubject":"communityInvolvementAndDevelopment",
                "data":[
                    {
                        "issueOfInterest":"educationAndCulture",
                        "rating":1
                    },
                    {
                        "issueOfInterest":"communityInvolvement",
                        "rating":2
                    },
                    {
                        "issueOfInterest":"employmentCreationAndSkillsDevelopment",
                        "rating":3
                    },
                    {
                        "issueOfInterest":"technologyDevelopmentAndAccess",
                        "rating":4
                    },
                    {
                        "issueOfInterest":"wealthAndIncomeCreation",
                        "rating":5
                    },
                    {
                        "issueOfInterest":"health",
                        "rating":6
                    },
                    {
                        "issueOfInterest":"socialInvestment",
                        "rating":7
                    }
                ]
            }
        ]
    },
]