// Update stakeholder results:
coreSubjectData:
[
    {"coreSubject":"organizationalGovernance","rating":1},
    {"coreSubject":"humanRights","rating":2},
    {"coreSubject":"laborPractices","rating":3},
    {"coreSubject":"theEnvironment","rating":4},
    {"coreSubject":"fairOperatingPractices","rating":5},
    {"coreSubject":"consumerIssues","rating":6},
    {"coreSubject":"communityInvolvementAndDevelopment","rating":7}
]
// Update stakeholder results:
issueOfInterestData: 
[
    {
        "coreSubject":"organizationalGovernance",
        "data":[
            {"issueOfInterest":"ethicalConduct","rating":1},
            {"issueOfInterest":"transparency","rating":2},
            {"issueOfInterest":"respectOfRuleOfLaw","rating":3},
            {"issueOfInterest":"accountability","rating":4},
            {"issueOfInterest":"corporateGovernance","rating":5}
        ]
    },
    {
        "coreSubject":"humanRights",
        "data":[
            {"issueOfInterest":"dueDiligence","rating":1},
            {"issueOfInterest":"humanRightsRisksSituations","rating":2},
            {"issueOfInterest":"avoindanceOfComplicity","rating":5},
            {"issueOfInterest":"resolvingGievances","rating":6},
            {"issueOfInterest":"discriminationAndVulnerableGroups","rating":3},
            {"issueOfInterest":"civilAndPoliticalRights","rating":4},
            {"issueOfInterest":"economicSocialAndCulturalRights","rating":7},
            {"issueOfInterest":"fundamentalPrinciplesAndRightsAtWork","rating":8}
        ]
    },
    {
        "coreSubject":"laborPractices",
        "data":[
            {"issueOfInterest":"employmentAndEmploymentRelationships","rating":1},
            {"issueOfInterest":"conditionsOfWorkAndSocialProtection","rating":2},
            {"issueOfInterest":"socialDialogue","rating":3},
            {"issueOfInterest":"healthAndSafetyAtWork","rating":4},
            {"issueOfInterest":"humanDevelopmentAndTrainingInTheWorkplace","rating":5}
        ]
    },
    {
        "coreSubject":"theEnvironment",
        "data":[
                {"issueOfInterest":"preventionOfPollution","rating":4},
                {"issueOfInterest":"sustainableResourceUse","rating":3},
                {"issueOfInterest":"climateChangeMitigationAndAdaptation","rating":1},
                {"issueOfInterest":"ProtectionOfTheEnvironmentBiodiversityAndRestorationOfNaturalHabitats","rating":2}
            ]
        },
        {
            "coreSubject":"fairOperatingPractices",
            "data":[
                {"issueOfInterest":"antiCorruption","rating":1},
                {"issueOfInterest":"responsiblePoliticalInvolvement","rating":4},
                {"issueOfInterest":"fairCompetition","rating":2},
                {"issueOfInterest":"promotingSocialResponsibilityInTheValueChain","rating":3},
                {"issueOfInterest":"respectForPropertyRights","rating":5}
            ]
        },
        {
            "coreSubject":"consumerIssues",
            "data":[
                {"issueOfInterest":"fairMarketingFactualAndUnbiasedInformati","rating":1},
                {"issueOfInterest":"protectingConsumersHealthAndSafety","rating":6},
                {"issueOfInterest":"sustainableConsumption","rating":4},
                {"issueOfInterest":"consumerServiceSupportAndComplai","rating":2},
                {"issueOfInterest":"consumerDataProtectionAndPrivacy","rating":3},
                {"issueOfInterest":"accessToEssentialServices","rating":5},
                {"issueOfInterest":"educationAndAwareness","rating":7}
            ]
        },
        {
            "coreSubject":"communityInvolvementAndDevelopment",
            "data":[
                {"issueOfInterest":"communityInvolvement","rating":1},
                {"issueOfInterest":"communityInvolvement","rating":4},
                {"issueOfInterest":"communityInvolvement","rating":5},
                {"issueOfInterest":"communityInvolvement","rating":3},
                {"issueOfInterest":"communityInvolvement","rating":2},
                {"issueOfInterest":"communityInvolvement","rating":6},
                {"issueOfInterest":"communityInvolvement","rating":7}
            ]
        }
]




// //////////////////////


// Update employee results:

coreSubjectData:
[
    {"coreSubject":"organizationalGovernance","rating":2},
    {"coreSubject":"humanRights","rating":1},
    {"coreSubject":"laborPractices","rating":3},
    {"coreSubject":"theEnvironment","rating":4},
    {"coreSubject":"fairOperatingPractices","rating":5},
    {"coreSubject":"consumerIssues","rating":6},
    {"coreSubject":"communityInvolvementAndDevelopment","rating":7}
]

// Update employee results: 

issueOfInterestData:
[
    {
        "coreSubject":"organizationalGovernance",
        "data":[
            {"issueOfInterest":"ethicalConduct","rating":1},
            {"issueOfInterest":"transparency","rating":4},
            {"issueOfInterest":"respectOfRuleOfLaw","rating":3},
            {"issueOfInterest":"accountability","rating":5},
            {"issueOfInterest":"corporateGovernance","rating":2}
        ]
    },
    {
        "coreSubject":"humanRights",
        "data":[
            {"issueOfInterest":"dueDiligence","rating":1},
            {"issueOfInterest":"humanRightsRisksSituations","rating":4},
            {"issueOfInterest":"avoindanceOfComplicity","rating":2},
            {"issueOfInterest":"resolvingGievances","rating":3},
            {"issueOfInterest":"discriminationAndVulnerableGroups","rating":6},
            {"issueOfInterest":"civilAndPoliticalRights","rating":7},
            {"issueOfInterest":"economicSocialAndCulturalRights","rating":5},
            {"issueOfInterest":"fundamentalPrinciplesAndRightsAtWork","rating":8}
        ]
    },
    {
        "coreSubject":"laborPractices",
        "data":[
            {"issueOfInterest":"employmentAndEmploymentRelationships","rating":1},
            {"issueOfInterest":"conditionsOfWorkAndSocialProtection","rating":5},
            {"issueOfInterest":"socialDialogue","rating":2},
            {"issueOfInterest":"healthAndSafetyAtWork","rating":3},
            {"issueOfInterest":"humanDevelopmentAndTrainingInTheWorkplace","rating":4}
        ]
    },
    {
        "coreSubject":"theEnvironment",
        "data":[
            {"issueOfInterest":"preventionOfPollution","rating":3},
            {"issueOfInterest":"sustainableResourceUse","rating":2},
            {"issueOfInterest":"climateChangeMitigationAndAdaptation","rating":1},
            {"issueOfInterest":"ProtectionOfTheEnvironmentBiodiversityAndRestorationOfNaturalHabitats","rating":4}
        ]
    },
    {
        "coreSubject":"fairOperatingPractices",
        "data":[
            {"issueOfInterest":"antiCorruption","rating":1},
            {"issueOfInterest":"responsiblePoliticalInvolvement","rating":2},
            {"issueOfInterest":"fairCompetition","rating":4},
            {"issueOfInterest":"promotingSocialResponsibilityInTheValueChain","rating":5},
            {"issueOfInterest":"respectForPropertyRights","rating":3}
        ]
    },
    {
        "coreSubject":"consumerIssues",
        "data":[
            {"issueOfInterest":"fairMarketingFactualAndUnbiasedInformati","rating":1},
            {"issueOfInterest":"protectingConsumersHealthAndSafety","rating":3},
            {"issueOfInterest":"sustainableConsumption","rating":2},
            {"issueOfInterest":"consumerServiceSupportAndComplai","rating":6},
            {"issueOfInterest":"consumerDataProtectionAndPrivacy",""consumerDataProtectionAndPrivacy","rating":4},
            {"issueOfInterest":"accessToEssentialSet":"educationAndAwareness","rating":rvices","rating":5},
            {"issueOfInterest":"educationAndAwareness","rating":7}
        ]
    },
    {
        "coreSubommunityInvolvement",
        "rating":1
    },
    {
        "coreSubject":"communityInvolvementAndDevelopment",
        "data":[
            {"issueOfInterest":"communityInvolvement","rating":3},
            {"issueOfInterestement","rating":1},
            {"issueOfInterest":"communityInvolvement","rating":2},
            {"issueOfInte":4},
            {"issueOfInterest":"communityInrest":"communityInvolvement","rating":3},
            {"issueOfInterest":"communityInvolvement","rating":6},
            {"issueOfInterest":"communityInvolvement","rating":4},
            {"issueOfInterest":"communityInvolvement","rating":5},
            {"issueOfInterest":"communityInvolvement","rating":7}
        ]
    }
]
